Train:
  batch_size: 128
  learning_rate: 0.01
  reg: 0
  epochs: 30

network:
  model: RNN # DNN or RNN or RandomForest


loss:
  loss_type: MSE # MSE or MAE

optimizer:
  optimizer_type: Adam # Adam or RMSProp