Train:
  batch_size: 1
  learning_rate: 0.00005
  reg: 0
  epoch: 10

network:
  model: DNN # DNN or RNN or RandomForest or LASSO or OLS


loss:
  loss_type: MSE # MSE or MAE

optimizer:
  optimizer_type: Adam # Adam or RMSProp