Train:
  batch_size: 128
  learning_rate: 0.01
  reg: 0
  epochs: 30
  steps: [4000, 25000]
  warmup: 0
  momentum: 0.9

network:
  model: MyModel # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: regular # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal